### ISSUE TITLE
Only got 24 cards?

### ISSUE THREAD

**Issue by hovikgas** [Dpananos/GetCards#7] opened 2019-03-29 18:09 UTC
Hi Demetri,

Thank you so much for posting this code! I tried it out and only got 24 cards and can't figure out what I did wrong... Any and all help would be greatly appreciated! Thanks again!

**Comment by Dpananos** [comment] 2019-03-29 19:34
Thanks for raising the issue.

When I run the notebook, only 25 are downloaded.  After some investigation, it seems that maybe the twitter API has changed. 

 On twitter, Chris links to the card through the text. "machinelearningflashcards.com".  That made it easy to identify which tweets were cards.  It seems that has changed and now when accessing the API from python, a url is showed.

I'll try and see if I can fix the notebook.  Your also welcome to fork the repo, find a solution, and make a PR.  I've got some other things on my plate, so no telling when I will get to this.

**Comment by Dpananos** [comment] 2019-03-29 19:41
The script seems to be working as designed for pulling cards from twitter.  However, I see when pulling tweets, only 286 are returned.  This could be a limitation of the twitter API, I don't know.

What you could do is use the `time` library to get around the rate limitation (if that is the problem).  

You could do something like

 
```{python}
while (True):
    time.sleep(5*60) #sleep needs time in seconds. Sleep 5 minutes before truing again
    more_tweets = api.user_timeline(screen_name='chrisalbon',
                                count=200,
                                include_rts=False,
                                exclude_replies=True,
                                max_id=last_id-1)
                                    
    # There are no more tweets
    if (len(more_tweets) == 0):
          break
    else:
        last_id = more_tweets[-1].id-1
        tweets += more_tweets
        
```

There may be another way to get more tweets, I'm not sure.  Feel free to investigate and make a PR.

**Comment by hovikgas** [comment] 2019-03-29 21:05
When I go to his Twitter page and scroll down, it won't let me see Tweets from before February 21.
<img width="608" alt="Screen Shot 2019-03-29 at 1 33 05 PM" src="https://user-images.githubusercontent.com/17107339/55261084-479a2f80-5227-11e9-89fe-94894fecd1b3.png">
Coincidentally, February 22 was the last card I downloaded: the IQR. So does Twitter archive old Tweets? I checked the Twitter API rate limits and I don't think we are crossing any of them, as they are listed [here](https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-user_timeline).

**Comment by Dpananos** [comment] 2019-03-29 21:14
Good catch.  I just tried pulling my own tweets, and the script works as expected.  This has something to do with Chris' account.  Maybe Chris deleted old tweets, maybe twitter is archiving them.  Either way, this is out of my control, and so if there is nothing else to address, I am closing the issue.

**Closed as completed by Dpananos** 2019-03-29 21:14 UTC
